const XML_TEMPLATE = '<?xml version="1.0" encoding="UTF-8"?><RME><ESTABLECIMIENTO_SALUD><NOMBRE>{NOMBRE}</NOMBRE><CODIGO_DEIS>{CODIGO_DEIS}</CODIGO_DEIS><TELEFONO>{TELEFONO}</TELEFONO><EMAIL>{EMAIL}</EMAIL><DIRECCION><CALLE>{CALLE}</CALLE><NUMERO>{NUMERO}</NUMERO><DEPARTAMENTO>{DEPARTAMENTO}</DEPARTAMENTO><COMUNA>{COMUNA}</COMUNA></DIRECCION></ESTABLECIMIENTO_SALUD><PROFESIONAL_PRESCRIPTOR><NOMBRE>{NOMBRE_PROFESIONAL}</NOMBRE><DOCUMENTO_IDENTIFICACION>RUN</DOCUMENTO_IDENTIFICACION><NUMERO_DOCUMENTO>{NUMERO_DOCUMENTO}</NUMERO_DOCUMENTO><PROFESION>{PROFESION}</PROFESION><NUMERO_REGISTRO_PRESTADORES_INDIVIDUALES_SI_SALUD>{NUMERO_REGISTRO_PRESTADORES_INDIVIDUALES_SI_SALUD}</NUMERO_REGISTRO_PRESTADORES_INDIVIDUALES_SI_SALUD><NUMERO_REGISTRO_COLEGIO_PROFESIONAL>{NUMERO_REGISTRO_COLEGIO_PROFESIONAL}</NUMERO_REGISTRO_COLEGIO_PROFESIONAL></PROFESIONAL_PRESCRIPTOR><PACIENTE><NOMBRE>{NOMBRE_PACIENTE}</NOMBRE><DOCUMENTO_IDENTIFICACION>{DOCUMENTO_IDENTIFICACION}</DOCUMENTO_IDENTIFICACION><NUMERO_DOCUMENTO>{NUMERO_DOCUMENTO}</NUMERO_DOCUMENTO><FECHA_NACIMIENTO>{FECHA_NACIMIENTO}</FECHA_NACIMIENTO><PESO>{PESO}</PESO><TALLA>{TALLA}</TALLA><DIRECCION>{DIRECCION}</DIRECCION><CIUDAD>{CIUDAD}</CIUDAD><TELEFONO>{TELEFONO}</TELEFONO></PACIENTE><PRESCRIPCIONES>{PRESCRIPCIONES}</PRESCRIPCIONES><DIAGNOSTICO>{DIAGNOSTICO}</DIAGNOSTICO><FECHA_PRESCRIPCION>{FECHA_PRESCRIPCION}</FECHA_PRESCRIPCION><INDICACIONES_AL_PACIENTE>{INDICACIONES_AL_PACIENTE}</INDICACIONES_AL_PACIENTE><INDICACIONES_AL_FARMACEUTICO>{INDICACIONES_AL_FARMACEUTICO}</INDICACIONES_AL_FARMACEUTICO><CONTRATO_DISPENSACION>{CONTRATO_DISPENSACION}</CONTRATO_DISPENSACION></RME>'

const XML_PRESCRIPTION = '<PRESCRIPCION><CODIGO_MEDICAMENTO>{CODIGO_MEDICAMENTO}</CODIGO_MEDICAMENTO><DOSIS>{DOSIS}</DOSIS><FRECUENCIA>{FRECUENCIA}</FRECUENCIA><DURACION_DE_LA_INDICACION>{DURACION_DE_LA_INDICACION}</DURACION_DE_LA_INDICACION></PRESCRIPCION>'

export function generateXML(object) {
  let xml = XML_TEMPLATE.replace('{NOMBRE}', object.name)
  return xml
}

export function sign(object) {
  return new Promise((resolve, reject) => {
    let xml = generateXML(object)
    console.log(xml)
    resolve('enviado')
  })

}
