export const DASHBOARD = '/private/dashboard'
export const HEADER = '/private'
export const CONFIGURATION = '/private/configuration'
export const SETTINGS = '/private/settings'
export const LOGIN = '/'
export const CREATE_ACCOUNT = '/account'
